message(STATUS "CMAKE_INCLUDE_FLAG_CXX: ${CMAKE_INCLUDE_FLAG_CXX}")
message(STATUS "CMAKE_INCLUDE_FLAG_C BEFORE: ${CMAKE_INCLUDE_FLAG_C}")
#
set(CMAKE_LIBRARY_PATH_FLAG "--include=")
set(CMAKE_INCLUDE_FLAG_C "--include=")
set(CMAKE_DEFINE_FLAG_C "--define=")
set(CMAKE_C_COMPILE_OBJECT  "<CMAKE_C_COMPILER> <SOURCE> <DEFINES> <INCLUDES> <FLAGS> -form=abs -output=<TARGET>.abs <OBJECTS>")
set(CMAKE_C_LINK_EXECUTABLE "<CMAKE_LINKER> -form=abs -output=<TARGET>.abs <OBJECTS>")
#
message(STATUS "CMAKE_INCLUDE_FLAG_CXX: ${CMAKE_INCLUDE_FLAG_CXX}")
message(STATUS "CMAKE_INCLUDE_FLAG_C AFTER: ${CMAKE_INCLUDE_FLAG_C}")