message(STATUS "CMAKE_INCLUDE_FLAG_CXX: ${CMAKE_INCLUDE_FLAG_CXX}")
message(STATUS "CMAKE_INCLUDE_FLAG_C BEFORE: ${CMAKE_INCLUDE_FLAG_C}")
#
set(CMAKE_INCLUDE_FLAG_C "--include=")
set(CMAKE_DEFINE_FLAG_C "--define=")
set(CMAKE_C_LINK_EXECUTABLE "<CMAKE_LINKER> -form=abs -output=<TARGET>.abs <OBJECTS>")
#
message(STATUS "CMAKE_INCLUDE_FLAG_CXX: ${CMAKE_INCLUDE_FLAG_CXX}")
message(STATUS "CMAKE_INCLUDE_FLAG_C AFTER: ${CMAKE_INCLUDE_FLAG_C}")