message(STATUS "CMAKE_INCLUDE_FLAG_CXX: ${CMAKE_INCLUDE_FLAG_CXX}")
message(STATUS "CMAKE_INCLUDE_FLAG_C: ${CMAKE_INCLUDE_FLAG_C}")
#
set(CMAKE_INCLUDE_FLAG_C "--include=")
set(CMAKE_DEFINE_FLAG_C "--define=")